env:
  global:
    - NODE_ENV=test

language: node_js

node_js:
  - "stable"

install:
  - npm install

script: 
  - npm test

after_success: npm run coverage

cache:
  directories:
    - 'node_modules'
  yarn: true

notifications:
  email: false
sudo: false

services:
  - postgresql

deploy:
  provider: script